// src/views/Setting.tsx
export default function SettingView() {
  return (
    <div className="card">
      <div className="card-header">change password</div>
      <div className="card-content">
        <div className="content">
          <div className="field is-horizontal">
            <div className="field-label is-normal"><label className="label">old password</label></div>
            <div className="field">
              <div className="control"><input type="password" /></div>
            </div>
          </div>
          <div className="field">
            <div className="control"><input type="password" /></div>
          </div>
        </div>
      </div>
    </div>
  )
}

// front/src/lib/setting.svelte
<main>
  <div class="card">
    <div class="card-header">change password</div>
    <div class="card-content">
      <div class="content">
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label" for="oldPassword">old password</label>
          </div>
          <div class="field">
            <div class="control">
              <input type="password" name="oldPassword" />
            </div>
          </div>
        </div>
        <div class="field is-horizontal">
          <div class="field-label is-normal">
            <label class="label" for="newPassword">new password</label>
          </div>
          <div class="field">
            <div class="control">
              <input type="password" name="newPassword" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
